services:
  ms2-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: ms2-app
    ports:
      - 3334:3000
    volumes:
      - .:/usr/src/app
      - ./docker/entrypoint.sh:/usr/src/app/entrypoint.sh
      - /usr/src/app/node_modules
    networks:
      - ms-network
    depends_on:
      ms2-postgres:
        condition: service_healthy
    environment:
      DATABASE_HOST: ms2-postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: ms_db
      DATABASE_SSL: false

  ms2-postgres:
    platform: linux/x86_64
    image: postgres:15
    container_name: ms2-postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "ms_db", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ms_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

networks:
  ms-network:
    driver: bridge
    name: ms-network
